//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sales
    {
        public tbl_Sales()
        {
            this.tbl_Orderstatus = new HashSet<tbl_Orderstatus>();
        }
    
        public int SalesId { get; set; }
        public Nullable<int> ProvId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<bool> PayStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Orderstatus { get; set; }
        public Nullable<double> TotalAmount { get; set; }
    
        public virtual tbl_Products tbl_Products { get; set; }
        public virtual tbl_Providers tbl_Providers { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual ICollection<tbl_Orderstatus> tbl_Orderstatus { get; set; }
    }
}
