//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Products
    {
        public tbl_Products()
        {
            this.tbl_Cart = new HashSet<tbl_Cart>();
            this.tbl_Sales = new HashSet<tbl_Sales>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<bool> Isdelete { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual tbl_Providers tbl_Providers { get; set; }
        public virtual ICollection<tbl_Cart> tbl_Cart { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual ICollection<tbl_Sales> tbl_Sales { get; set; }
    }
}
