//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bank
    {
        public int BankId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> CVC { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
    }
}
