//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Login
    {
        public tbl_Login()
        {
            this.tbl_User = new HashSet<tbl_User>();
            this.tbl_Providers = new HashSet<tbl_Providers>();
            this.tbl_bank = new HashSet<tbl_bank>();
        }
    
        public int LogId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<bool> Isdelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> role { get; set; }
    
        public virtual ICollection<tbl_User> tbl_User { get; set; }
        public virtual ICollection<tbl_Providers> tbl_Providers { get; set; }
        public virtual ICollection<tbl_bank> tbl_bank { get; set; }
    }
}
